// flow-typed signature: b8d688b985e37ed86ab30ecff13427fb
// flow-typed version: <<STUB>>/ajv-keywords_v3.4.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ajv-keywords'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ajv-keywords' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ajv-keywords/keywords/_formatLimit' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/_util' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/allRequired' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/anyRequired' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/deepProperties' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/deepRequired' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/dotjs/_formatLimit' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/dotjs/patternRequired' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/dotjs/switch' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/dynamicDefaults' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/formatMaximum' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/formatMinimum' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/index' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/instanceof' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/patternRequired' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/prohibited' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/range' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/regexp' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/select' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/switch' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/transform' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/typeof' {
  declare module.exports: any;
}

declare module 'ajv-keywords/keywords/uniqueItemProperties' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ajv-keywords/index' {
  declare module.exports: $Exports<'ajv-keywords'>;
}
declare module 'ajv-keywords/index.js' {
  declare module.exports: $Exports<'ajv-keywords'>;
}
declare module 'ajv-keywords/keywords/_formatLimit.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/_formatLimit'>;
}
declare module 'ajv-keywords/keywords/_util.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/_util'>;
}
declare module 'ajv-keywords/keywords/allRequired.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/allRequired'>;
}
declare module 'ajv-keywords/keywords/anyRequired.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/anyRequired'>;
}
declare module 'ajv-keywords/keywords/deepProperties.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/deepProperties'>;
}
declare module 'ajv-keywords/keywords/deepRequired.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/deepRequired'>;
}
declare module 'ajv-keywords/keywords/dotjs/_formatLimit.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/dotjs/_formatLimit'>;
}
declare module 'ajv-keywords/keywords/dotjs/patternRequired.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/dotjs/patternRequired'>;
}
declare module 'ajv-keywords/keywords/dotjs/switch.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/dotjs/switch'>;
}
declare module 'ajv-keywords/keywords/dynamicDefaults.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/dynamicDefaults'>;
}
declare module 'ajv-keywords/keywords/formatMaximum.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/formatMaximum'>;
}
declare module 'ajv-keywords/keywords/formatMinimum.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/formatMinimum'>;
}
declare module 'ajv-keywords/keywords/index.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/index'>;
}
declare module 'ajv-keywords/keywords/instanceof.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/instanceof'>;
}
declare module 'ajv-keywords/keywords/patternRequired.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/patternRequired'>;
}
declare module 'ajv-keywords/keywords/prohibited.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/prohibited'>;
}
declare module 'ajv-keywords/keywords/range.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/range'>;
}
declare module 'ajv-keywords/keywords/regexp.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/regexp'>;
}
declare module 'ajv-keywords/keywords/select.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/select'>;
}
declare module 'ajv-keywords/keywords/switch.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/switch'>;
}
declare module 'ajv-keywords/keywords/transform.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/transform'>;
}
declare module 'ajv-keywords/keywords/typeof.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/typeof'>;
}
declare module 'ajv-keywords/keywords/uniqueItemProperties.js' {
  declare module.exports: $Exports<'ajv-keywords/keywords/uniqueItemProperties'>;
}
