// flow-typed signature: c7b9a9a19fad06c9cb073a91f52a7011
// flow-typed version: <<STUB>>/baobab_v2.5.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'baobab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'baobab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'baobab/dist/baobab' {
  declare module.exports: any;
}

declare module 'baobab/dist/cursor' {
  declare module.exports: any;
}

declare module 'baobab/dist/helpers' {
  declare module.exports: any;
}

declare module 'baobab/dist/monkey' {
  declare module.exports: any;
}

declare module 'baobab/dist/type' {
  declare module.exports: any;
}

declare module 'baobab/dist/update' {
  declare module.exports: any;
}

declare module 'baobab/dist/watcher' {
  declare module.exports: any;
}

declare module 'baobab/eslint.config' {
  declare module.exports: any;
}

declare module 'baobab/scripts/banner' {
  declare module.exports: any;
}

declare module 'baobab/src/baobab' {
  declare module.exports: any;
}

declare module 'baobab/src/cursor' {
  declare module.exports: any;
}

declare module 'baobab/src/helpers' {
  declare module.exports: any;
}

declare module 'baobab/src/monkey' {
  declare module.exports: any;
}

declare module 'baobab/src/type' {
  declare module.exports: any;
}

declare module 'baobab/src/update' {
  declare module.exports: any;
}

declare module 'baobab/src/watcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'baobab/dist/baobab.js' {
  declare module.exports: $Exports<'baobab/dist/baobab'>;
}
declare module 'baobab/dist/cursor.js' {
  declare module.exports: $Exports<'baobab/dist/cursor'>;
}
declare module 'baobab/dist/helpers.js' {
  declare module.exports: $Exports<'baobab/dist/helpers'>;
}
declare module 'baobab/dist/monkey.js' {
  declare module.exports: $Exports<'baobab/dist/monkey'>;
}
declare module 'baobab/dist/type.js' {
  declare module.exports: $Exports<'baobab/dist/type'>;
}
declare module 'baobab/dist/update.js' {
  declare module.exports: $Exports<'baobab/dist/update'>;
}
declare module 'baobab/dist/watcher.js' {
  declare module.exports: $Exports<'baobab/dist/watcher'>;
}
declare module 'baobab/eslint.config.js' {
  declare module.exports: $Exports<'baobab/eslint.config'>;
}
declare module 'baobab/scripts/banner.js' {
  declare module.exports: $Exports<'baobab/scripts/banner'>;
}
declare module 'baobab/src/baobab.js' {
  declare module.exports: $Exports<'baobab/src/baobab'>;
}
declare module 'baobab/src/cursor.js' {
  declare module.exports: $Exports<'baobab/src/cursor'>;
}
declare module 'baobab/src/helpers.js' {
  declare module.exports: $Exports<'baobab/src/helpers'>;
}
declare module 'baobab/src/monkey.js' {
  declare module.exports: $Exports<'baobab/src/monkey'>;
}
declare module 'baobab/src/type.js' {
  declare module.exports: $Exports<'baobab/src/type'>;
}
declare module 'baobab/src/update.js' {
  declare module.exports: $Exports<'baobab/src/update'>;
}
declare module 'baobab/src/watcher.js' {
  declare module.exports: $Exports<'baobab/src/watcher'>;
}
