// flow-typed signature: 537cb753b9ca2a6efd271ac5ee161a94
// flow-typed version: <<STUB>>/connect_v3.6.6/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'connect/index' {
  declare module.exports: $Exports<'connect'>;
}
declare module 'connect/index.js' {
  declare module.exports: $Exports<'connect'>;
}
