// flow-typed signature: 0e00f7abefea9ff34f6d9bf951350af5
// flow-typed version: <<STUB>>/cssnano-preset-advanced_v4.0.0-rc.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssnano-preset-advanced'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssnano-preset-advanced' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cssnano-preset-advanced/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cssnano-preset-advanced/dist/index.js' {
  declare module.exports: $Exports<'cssnano-preset-advanced/dist/index'>;
}
