// flow-typed signature: 35b96f2cc88576c9007a7a138b4e7188
// flow-typed version: <<STUB>>/eslint-config-vazco_v4.2.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-vazco'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-vazco' {
  declare module.exports: any;
}
