// flow-typed signature: 4b1b12784b3c32b6cb7b482eaec3df35
// flow-typed version: <<STUB>>/eslint-config-vazco_v4.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-vazco'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-vazco' {
  declare module.exports: any;
}
