// flow-typed signature: 7fd2c1b2dfdeba7f7d3c38b4ca95ef67
// flow-typed version: <<STUB>>/etag_v1.8.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'etag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'etag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'etag/index' {
  declare module.exports: $Exports<'etag'>;
}
declare module 'etag/index.js' {
  declare module.exports: $Exports<'etag'>;
}
