// flow-typed signature: e1a009a817e3b9b69beb706e5a533a4c
// flow-typed version: <<STUB>>/html-minifier_v3.5.13/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-minifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-minifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-minifier/cli' {
  declare module.exports: any;
}

declare module 'html-minifier/src/htmlminifier' {
  declare module.exports: any;
}

declare module 'html-minifier/src/htmlparser' {
  declare module.exports: any;
}

declare module 'html-minifier/src/tokenchain' {
  declare module.exports: any;
}

declare module 'html-minifier/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-minifier/cli.js' {
  declare module.exports: $Exports<'html-minifier/cli'>;
}
declare module 'html-minifier/src/htmlminifier.js' {
  declare module.exports: $Exports<'html-minifier/src/htmlminifier'>;
}
declare module 'html-minifier/src/htmlparser.js' {
  declare module.exports: $Exports<'html-minifier/src/htmlparser'>;
}
declare module 'html-minifier/src/tokenchain.js' {
  declare module.exports: $Exports<'html-minifier/src/tokenchain'>;
}
declare module 'html-minifier/src/utils.js' {
  declare module.exports: $Exports<'html-minifier/src/utils'>;
}
