// flow-typed signature: 93494b488c0d3eaed2c1496dc66966d5
// flow-typed version: <<STUB>>/mongodb_v3.2.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongodb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongodb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongodb/lib/admin' {
  declare module.exports: any;
}

declare module 'mongodb/lib/aggregation_cursor' {
  declare module.exports: any;
}

declare module 'mongodb/lib/apm' {
  declare module.exports: any;
}

declare module 'mongodb/lib/async/async_iterator' {
  declare module.exports: any;
}

declare module 'mongodb/lib/bulk/common' {
  declare module.exports: any;
}

declare module 'mongodb/lib/bulk/ordered' {
  declare module.exports: any;
}

declare module 'mongodb/lib/bulk/unordered' {
  declare module.exports: any;
}

declare module 'mongodb/lib/change_stream' {
  declare module.exports: any;
}

declare module 'mongodb/lib/collection' {
  declare module.exports: any;
}

declare module 'mongodb/lib/command_cursor' {
  declare module.exports: any;
}

declare module 'mongodb/lib/constants' {
  declare module.exports: any;
}

declare module 'mongodb/lib/cursor' {
  declare module.exports: any;
}

declare module 'mongodb/lib/db' {
  declare module.exports: any;
}

declare module 'mongodb/lib/error' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs-stream/download' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs-stream/index' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs-stream/upload' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs/chunk' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs/grid_store' {
  declare module.exports: any;
}

declare module 'mongodb/lib/mongo_client' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/admin_ops' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/aggregate' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/collection_ops' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/cursor_ops' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/db_ops' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/mongo_client_ops' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topologies/mongos' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topologies/native_topology' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topologies/replset' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topologies/server' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topologies/topology_base' {
  declare module.exports: any;
}

declare module 'mongodb/lib/url_parser' {
  declare module.exports: any;
}

declare module 'mongodb/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongodb/index' {
  declare module.exports: $Exports<'mongodb'>;
}
declare module 'mongodb/index.js' {
  declare module.exports: $Exports<'mongodb'>;
}
declare module 'mongodb/lib/admin.js' {
  declare module.exports: $Exports<'mongodb/lib/admin'>;
}
declare module 'mongodb/lib/aggregation_cursor.js' {
  declare module.exports: $Exports<'mongodb/lib/aggregation_cursor'>;
}
declare module 'mongodb/lib/apm.js' {
  declare module.exports: $Exports<'mongodb/lib/apm'>;
}
declare module 'mongodb/lib/async/async_iterator.js' {
  declare module.exports: $Exports<'mongodb/lib/async/async_iterator'>;
}
declare module 'mongodb/lib/bulk/common.js' {
  declare module.exports: $Exports<'mongodb/lib/bulk/common'>;
}
declare module 'mongodb/lib/bulk/ordered.js' {
  declare module.exports: $Exports<'mongodb/lib/bulk/ordered'>;
}
declare module 'mongodb/lib/bulk/unordered.js' {
  declare module.exports: $Exports<'mongodb/lib/bulk/unordered'>;
}
declare module 'mongodb/lib/change_stream.js' {
  declare module.exports: $Exports<'mongodb/lib/change_stream'>;
}
declare module 'mongodb/lib/collection.js' {
  declare module.exports: $Exports<'mongodb/lib/collection'>;
}
declare module 'mongodb/lib/command_cursor.js' {
  declare module.exports: $Exports<'mongodb/lib/command_cursor'>;
}
declare module 'mongodb/lib/constants.js' {
  declare module.exports: $Exports<'mongodb/lib/constants'>;
}
declare module 'mongodb/lib/cursor.js' {
  declare module.exports: $Exports<'mongodb/lib/cursor'>;
}
declare module 'mongodb/lib/db.js' {
  declare module.exports: $Exports<'mongodb/lib/db'>;
}
declare module 'mongodb/lib/error.js' {
  declare module.exports: $Exports<'mongodb/lib/error'>;
}
declare module 'mongodb/lib/gridfs-stream/download.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs-stream/download'>;
}
declare module 'mongodb/lib/gridfs-stream/index.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs-stream/index'>;
}
declare module 'mongodb/lib/gridfs-stream/upload.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs-stream/upload'>;
}
declare module 'mongodb/lib/gridfs/chunk.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs/chunk'>;
}
declare module 'mongodb/lib/gridfs/grid_store.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs/grid_store'>;
}
declare module 'mongodb/lib/mongo_client.js' {
  declare module.exports: $Exports<'mongodb/lib/mongo_client'>;
}
declare module 'mongodb/lib/operations/admin_ops.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/admin_ops'>;
}
declare module 'mongodb/lib/operations/aggregate.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/aggregate'>;
}
declare module 'mongodb/lib/operations/collection_ops.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/collection_ops'>;
}
declare module 'mongodb/lib/operations/cursor_ops.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/cursor_ops'>;
}
declare module 'mongodb/lib/operations/db_ops.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/db_ops'>;
}
declare module 'mongodb/lib/operations/mongo_client_ops.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/mongo_client_ops'>;
}
declare module 'mongodb/lib/topologies/mongos.js' {
  declare module.exports: $Exports<'mongodb/lib/topologies/mongos'>;
}
declare module 'mongodb/lib/topologies/native_topology.js' {
  declare module.exports: $Exports<'mongodb/lib/topologies/native_topology'>;
}
declare module 'mongodb/lib/topologies/replset.js' {
  declare module.exports: $Exports<'mongodb/lib/topologies/replset'>;
}
declare module 'mongodb/lib/topologies/server.js' {
  declare module.exports: $Exports<'mongodb/lib/topologies/server'>;
}
declare module 'mongodb/lib/topologies/topology_base.js' {
  declare module.exports: $Exports<'mongodb/lib/topologies/topology_base'>;
}
declare module 'mongodb/lib/url_parser.js' {
  declare module.exports: $Exports<'mongodb/lib/url_parser'>;
}
declare module 'mongodb/lib/utils.js' {
  declare module.exports: $Exports<'mongodb/lib/utils'>;
}
