// flow-typed signature: e0da074ac8faae1f26f2a9fa812d4bfb
// flow-typed version: <<STUB>>/mup-disk_v0.2.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mup-disk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mup-disk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mup-disk/command-handlers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mup-disk/command-handlers.js' {
  declare module.exports: $Exports<'mup-disk/command-handlers'>;
}
declare module 'mup-disk/index' {
  declare module.exports: $Exports<'mup-disk'>;
}
declare module 'mup-disk/index.js' {
  declare module.exports: $Exports<'mup-disk'>;
}
