// flow-typed signature: 0a8eecba8aee3c46d03a48021063ad1f
// flow-typed version: <<STUB>>/mup_v1.4.4/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mup/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'mup/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'mup/docs/_site/examples/basic' {
  declare module.exports: any;
}

declare module 'mup/docs/_site/scripts/bootstrap.min' {
  declare module.exports: any;
}

declare module 'mup/docs/_site/scripts/github-request' {
  declare module.exports: any;
}

declare module 'mup/docs/_site/scripts/jquery-3.2.1.min' {
  declare module.exports: any;
}

declare module 'mup/docs/_site/scripts/toc-bot' {
  declare module.exports: any;
}

declare module 'mup/docs/_site/scripts/tocbot' {
  declare module.exports: any;
}

declare module 'mup/docs/_site/scripts/tocbot.min' {
  declare module.exports: any;
}

declare module 'mup/docs/examples/basic' {
  declare module.exports: any;
}

declare module 'mup/docs/scripts/bootstrap.min' {
  declare module.exports: any;
}

declare module 'mup/docs/scripts/github-request' {
  declare module.exports: any;
}

declare module 'mup/docs/scripts/jquery-3.2.1.min' {
  declare module.exports: any;
}

declare module 'mup/docs/scripts/toc-bot' {
  declare module.exports: any;
}

declare module 'mup/docs/scripts/tocbot' {
  declare module.exports: any;
}

declare module 'mup/docs/scripts/tocbot.min' {
  declare module.exports: any;
}

declare module 'mup/lib/__tests__/commands.unit' {
  declare module.exports: any;
}

declare module 'mup/lib/__tests__/hooks.unit' {
  declare module.exports: any;
}

declare module 'mup/lib/__tests__/load-plugins.unit' {
  declare module.exports: any;
}

declare module 'mup/lib/__tests__/plugin-api.unit' {
  declare module.exports: any;
}

declare module 'mup/lib/__tests__/prepare-config.unit' {
  declare module.exports: any;
}

declare module 'mup/lib/__tests__/scrub-config.unit' {
  declare module.exports: any;
}

declare module 'mup/lib/__tests__/utils.unit' {
  declare module.exports: any;
}

declare module 'mup/lib/commands' {
  declare module.exports: any;
}

declare module 'mup/lib/hooks' {
  declare module.exports: any;
}

declare module 'mup/lib/index' {
  declare module.exports: any;
}

declare module 'mup/lib/load-plugins' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/default/__tests__/index' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/default/index' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/docker/__tests__/index' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/docker/index' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/index' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/meteor/__tests__/index' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/meteor/build' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/meteor/index' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/mongo/__tests__/index' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/mongo/index' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/proxy/index' {
  declare module.exports: any;
}

declare module 'mup/lib/modules/utils' {
  declare module.exports: any;
}

declare module 'mup/lib/mup-api' {
  declare module.exports: any;
}

declare module 'mup/lib/node-version' {
  declare module.exports: any;
}

declare module 'mup/lib/nodemiral' {
  declare module.exports: any;
}

declare module 'mup/lib/plugin-api' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/default/__tests__/index' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/default/command-handlers' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/default/commands' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/default/index' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/default/init' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/docker/__tests__/index' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/docker/command-handlers' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/docker/commands' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/docker/index' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/docker/swarm' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/docker/utils' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/meteor/__tests__/index' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/meteor/build' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/meteor/command-handlers' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/meteor/commands' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/meteor/index' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/meteor/status' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/meteor/utils' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/meteor/validate' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/mongo/__tests__/index' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/mongo/command-handlers' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/mongo/commands' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/mongo/index' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/mongo/validate' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/proxy/__tests__/index' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/proxy/command-handlers' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/proxy/commands' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/proxy/index' {
  declare module.exports: any;
}

declare module 'mup/lib/plugins/proxy/validate' {
  declare module.exports: any;
}

declare module 'mup/lib/prepare-config' {
  declare module.exports: any;
}

declare module 'mup/lib/scrub-config' {
  declare module.exports: any;
}

declare module 'mup/lib/server-info' {
  declare module.exports: any;
}

declare module 'mup/lib/swarm-options' {
  declare module.exports: any;
}

declare module 'mup/lib/swarm-utils' {
  declare module.exports: any;
}

declare module 'mup/lib/updates' {
  declare module.exports: any;
}

declare module 'mup/lib/utils' {
  declare module.exports: any;
}

declare module 'mup/lib/validate/__tests__/index.unit' {
  declare module.exports: any;
}

declare module 'mup/lib/validate/__tests__/utils.unit' {
  declare module.exports: any;
}

declare module 'mup/lib/validate/index' {
  declare module.exports: any;
}

declare module 'mup/lib/validate/meteor' {
  declare module.exports: any;
}

declare module 'mup/lib/validate/mongo' {
  declare module.exports: any;
}

declare module 'mup/lib/validate/proxy' {
  declare module.exports: any;
}

declare module 'mup/lib/validate/servers' {
  declare module.exports: any;
}

declare module 'mup/lib/validate/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mup/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'mup/coverage/lcov-report/prettify'>;
}
declare module 'mup/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'mup/coverage/lcov-report/sorter'>;
}
declare module 'mup/docs/_site/examples/basic.js' {
  declare module.exports: $Exports<'mup/docs/_site/examples/basic'>;
}
declare module 'mup/docs/_site/scripts/bootstrap.min.js' {
  declare module.exports: $Exports<'mup/docs/_site/scripts/bootstrap.min'>;
}
declare module 'mup/docs/_site/scripts/github-request.js' {
  declare module.exports: $Exports<'mup/docs/_site/scripts/github-request'>;
}
declare module 'mup/docs/_site/scripts/jquery-3.2.1.min.js' {
  declare module.exports: $Exports<'mup/docs/_site/scripts/jquery-3.2.1.min'>;
}
declare module 'mup/docs/_site/scripts/toc-bot.js' {
  declare module.exports: $Exports<'mup/docs/_site/scripts/toc-bot'>;
}
declare module 'mup/docs/_site/scripts/tocbot.js' {
  declare module.exports: $Exports<'mup/docs/_site/scripts/tocbot'>;
}
declare module 'mup/docs/_site/scripts/tocbot.min.js' {
  declare module.exports: $Exports<'mup/docs/_site/scripts/tocbot.min'>;
}
declare module 'mup/docs/examples/basic.js' {
  declare module.exports: $Exports<'mup/docs/examples/basic'>;
}
declare module 'mup/docs/scripts/bootstrap.min.js' {
  declare module.exports: $Exports<'mup/docs/scripts/bootstrap.min'>;
}
declare module 'mup/docs/scripts/github-request.js' {
  declare module.exports: $Exports<'mup/docs/scripts/github-request'>;
}
declare module 'mup/docs/scripts/jquery-3.2.1.min.js' {
  declare module.exports: $Exports<'mup/docs/scripts/jquery-3.2.1.min'>;
}
declare module 'mup/docs/scripts/toc-bot.js' {
  declare module.exports: $Exports<'mup/docs/scripts/toc-bot'>;
}
declare module 'mup/docs/scripts/tocbot.js' {
  declare module.exports: $Exports<'mup/docs/scripts/tocbot'>;
}
declare module 'mup/docs/scripts/tocbot.min.js' {
  declare module.exports: $Exports<'mup/docs/scripts/tocbot.min'>;
}
declare module 'mup/index' {
  declare module.exports: $Exports<'mup'>;
}
declare module 'mup/index.js' {
  declare module.exports: $Exports<'mup'>;
}
declare module 'mup/lib/__tests__/commands.unit.js' {
  declare module.exports: $Exports<'mup/lib/__tests__/commands.unit'>;
}
declare module 'mup/lib/__tests__/hooks.unit.js' {
  declare module.exports: $Exports<'mup/lib/__tests__/hooks.unit'>;
}
declare module 'mup/lib/__tests__/load-plugins.unit.js' {
  declare module.exports: $Exports<'mup/lib/__tests__/load-plugins.unit'>;
}
declare module 'mup/lib/__tests__/plugin-api.unit.js' {
  declare module.exports: $Exports<'mup/lib/__tests__/plugin-api.unit'>;
}
declare module 'mup/lib/__tests__/prepare-config.unit.js' {
  declare module.exports: $Exports<'mup/lib/__tests__/prepare-config.unit'>;
}
declare module 'mup/lib/__tests__/scrub-config.unit.js' {
  declare module.exports: $Exports<'mup/lib/__tests__/scrub-config.unit'>;
}
declare module 'mup/lib/__tests__/utils.unit.js' {
  declare module.exports: $Exports<'mup/lib/__tests__/utils.unit'>;
}
declare module 'mup/lib/commands.js' {
  declare module.exports: $Exports<'mup/lib/commands'>;
}
declare module 'mup/lib/hooks.js' {
  declare module.exports: $Exports<'mup/lib/hooks'>;
}
declare module 'mup/lib/index.js' {
  declare module.exports: $Exports<'mup/lib/index'>;
}
declare module 'mup/lib/load-plugins.js' {
  declare module.exports: $Exports<'mup/lib/load-plugins'>;
}
declare module 'mup/lib/modules/default/__tests__/index.js' {
  declare module.exports: $Exports<'mup/lib/modules/default/__tests__/index'>;
}
declare module 'mup/lib/modules/default/index.js' {
  declare module.exports: $Exports<'mup/lib/modules/default/index'>;
}
declare module 'mup/lib/modules/docker/__tests__/index.js' {
  declare module.exports: $Exports<'mup/lib/modules/docker/__tests__/index'>;
}
declare module 'mup/lib/modules/docker/index.js' {
  declare module.exports: $Exports<'mup/lib/modules/docker/index'>;
}
declare module 'mup/lib/modules/index.js' {
  declare module.exports: $Exports<'mup/lib/modules/index'>;
}
declare module 'mup/lib/modules/meteor/__tests__/index.js' {
  declare module.exports: $Exports<'mup/lib/modules/meteor/__tests__/index'>;
}
declare module 'mup/lib/modules/meteor/build.js' {
  declare module.exports: $Exports<'mup/lib/modules/meteor/build'>;
}
declare module 'mup/lib/modules/meteor/index.js' {
  declare module.exports: $Exports<'mup/lib/modules/meteor/index'>;
}
declare module 'mup/lib/modules/mongo/__tests__/index.js' {
  declare module.exports: $Exports<'mup/lib/modules/mongo/__tests__/index'>;
}
declare module 'mup/lib/modules/mongo/index.js' {
  declare module.exports: $Exports<'mup/lib/modules/mongo/index'>;
}
declare module 'mup/lib/modules/proxy/index.js' {
  declare module.exports: $Exports<'mup/lib/modules/proxy/index'>;
}
declare module 'mup/lib/modules/utils.js' {
  declare module.exports: $Exports<'mup/lib/modules/utils'>;
}
declare module 'mup/lib/mup-api.js' {
  declare module.exports: $Exports<'mup/lib/mup-api'>;
}
declare module 'mup/lib/node-version.js' {
  declare module.exports: $Exports<'mup/lib/node-version'>;
}
declare module 'mup/lib/nodemiral.js' {
  declare module.exports: $Exports<'mup/lib/nodemiral'>;
}
declare module 'mup/lib/plugin-api.js' {
  declare module.exports: $Exports<'mup/lib/plugin-api'>;
}
declare module 'mup/lib/plugins/default/__tests__/index.js' {
  declare module.exports: $Exports<'mup/lib/plugins/default/__tests__/index'>;
}
declare module 'mup/lib/plugins/default/command-handlers.js' {
  declare module.exports: $Exports<'mup/lib/plugins/default/command-handlers'>;
}
declare module 'mup/lib/plugins/default/commands.js' {
  declare module.exports: $Exports<'mup/lib/plugins/default/commands'>;
}
declare module 'mup/lib/plugins/default/index.js' {
  declare module.exports: $Exports<'mup/lib/plugins/default/index'>;
}
declare module 'mup/lib/plugins/default/init.js' {
  declare module.exports: $Exports<'mup/lib/plugins/default/init'>;
}
declare module 'mup/lib/plugins/docker/__tests__/index.js' {
  declare module.exports: $Exports<'mup/lib/plugins/docker/__tests__/index'>;
}
declare module 'mup/lib/plugins/docker/command-handlers.js' {
  declare module.exports: $Exports<'mup/lib/plugins/docker/command-handlers'>;
}
declare module 'mup/lib/plugins/docker/commands.js' {
  declare module.exports: $Exports<'mup/lib/plugins/docker/commands'>;
}
declare module 'mup/lib/plugins/docker/index.js' {
  declare module.exports: $Exports<'mup/lib/plugins/docker/index'>;
}
declare module 'mup/lib/plugins/docker/swarm.js' {
  declare module.exports: $Exports<'mup/lib/plugins/docker/swarm'>;
}
declare module 'mup/lib/plugins/docker/utils.js' {
  declare module.exports: $Exports<'mup/lib/plugins/docker/utils'>;
}
declare module 'mup/lib/plugins/meteor/__tests__/index.js' {
  declare module.exports: $Exports<'mup/lib/plugins/meteor/__tests__/index'>;
}
declare module 'mup/lib/plugins/meteor/build.js' {
  declare module.exports: $Exports<'mup/lib/plugins/meteor/build'>;
}
declare module 'mup/lib/plugins/meteor/command-handlers.js' {
  declare module.exports: $Exports<'mup/lib/plugins/meteor/command-handlers'>;
}
declare module 'mup/lib/plugins/meteor/commands.js' {
  declare module.exports: $Exports<'mup/lib/plugins/meteor/commands'>;
}
declare module 'mup/lib/plugins/meteor/index.js' {
  declare module.exports: $Exports<'mup/lib/plugins/meteor/index'>;
}
declare module 'mup/lib/plugins/meteor/status.js' {
  declare module.exports: $Exports<'mup/lib/plugins/meteor/status'>;
}
declare module 'mup/lib/plugins/meteor/utils.js' {
  declare module.exports: $Exports<'mup/lib/plugins/meteor/utils'>;
}
declare module 'mup/lib/plugins/meteor/validate.js' {
  declare module.exports: $Exports<'mup/lib/plugins/meteor/validate'>;
}
declare module 'mup/lib/plugins/mongo/__tests__/index.js' {
  declare module.exports: $Exports<'mup/lib/plugins/mongo/__tests__/index'>;
}
declare module 'mup/lib/plugins/mongo/command-handlers.js' {
  declare module.exports: $Exports<'mup/lib/plugins/mongo/command-handlers'>;
}
declare module 'mup/lib/plugins/mongo/commands.js' {
  declare module.exports: $Exports<'mup/lib/plugins/mongo/commands'>;
}
declare module 'mup/lib/plugins/mongo/index.js' {
  declare module.exports: $Exports<'mup/lib/plugins/mongo/index'>;
}
declare module 'mup/lib/plugins/mongo/validate.js' {
  declare module.exports: $Exports<'mup/lib/plugins/mongo/validate'>;
}
declare module 'mup/lib/plugins/proxy/__tests__/index.js' {
  declare module.exports: $Exports<'mup/lib/plugins/proxy/__tests__/index'>;
}
declare module 'mup/lib/plugins/proxy/command-handlers.js' {
  declare module.exports: $Exports<'mup/lib/plugins/proxy/command-handlers'>;
}
declare module 'mup/lib/plugins/proxy/commands.js' {
  declare module.exports: $Exports<'mup/lib/plugins/proxy/commands'>;
}
declare module 'mup/lib/plugins/proxy/index.js' {
  declare module.exports: $Exports<'mup/lib/plugins/proxy/index'>;
}
declare module 'mup/lib/plugins/proxy/validate.js' {
  declare module.exports: $Exports<'mup/lib/plugins/proxy/validate'>;
}
declare module 'mup/lib/prepare-config.js' {
  declare module.exports: $Exports<'mup/lib/prepare-config'>;
}
declare module 'mup/lib/scrub-config.js' {
  declare module.exports: $Exports<'mup/lib/scrub-config'>;
}
declare module 'mup/lib/server-info.js' {
  declare module.exports: $Exports<'mup/lib/server-info'>;
}
declare module 'mup/lib/swarm-options.js' {
  declare module.exports: $Exports<'mup/lib/swarm-options'>;
}
declare module 'mup/lib/swarm-utils.js' {
  declare module.exports: $Exports<'mup/lib/swarm-utils'>;
}
declare module 'mup/lib/updates.js' {
  declare module.exports: $Exports<'mup/lib/updates'>;
}
declare module 'mup/lib/utils.js' {
  declare module.exports: $Exports<'mup/lib/utils'>;
}
declare module 'mup/lib/validate/__tests__/index.unit.js' {
  declare module.exports: $Exports<'mup/lib/validate/__tests__/index.unit'>;
}
declare module 'mup/lib/validate/__tests__/utils.unit.js' {
  declare module.exports: $Exports<'mup/lib/validate/__tests__/utils.unit'>;
}
declare module 'mup/lib/validate/index.js' {
  declare module.exports: $Exports<'mup/lib/validate/index'>;
}
declare module 'mup/lib/validate/meteor.js' {
  declare module.exports: $Exports<'mup/lib/validate/meteor'>;
}
declare module 'mup/lib/validate/mongo.js' {
  declare module.exports: $Exports<'mup/lib/validate/mongo'>;
}
declare module 'mup/lib/validate/proxy.js' {
  declare module.exports: $Exports<'mup/lib/validate/proxy'>;
}
declare module 'mup/lib/validate/servers.js' {
  declare module.exports: $Exports<'mup/lib/validate/servers'>;
}
declare module 'mup/lib/validate/utils.js' {
  declare module.exports: $Exports<'mup/lib/validate/utils'>;
}
