// flow-typed signature: b2529ebb382ade7aa2a53b99b3a37832
// flow-typed version: <<STUB>>/parcel-plugin-inline-css_vfile:packages/parcel-plugin-inline-css/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parcel-plugin-inline-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parcel-plugin-inline-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parcel-plugin-inline-css/index' {
  declare module.exports: $Exports<'parcel-plugin-inline-css'>;
}
declare module 'parcel-plugin-inline-css/index.js' {
  declare module.exports: $Exports<'parcel-plugin-inline-css'>;
}
