// flow-typed signature: a2a7340ada638588b39fcf744e1fb0b6
// flow-typed version: <<STUB>>/postcss-custom-properties_v8.0.8/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-custom-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-custom-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-custom-properties/index.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-custom-properties/index.cjs.js' {
  declare module.exports: $Exports<'postcss-custom-properties/index.cjs'>;
}
