// flow-typed signature: d142c3023ed5caa79b975314b26f0478
// flow-typed version: <<STUB>>/postcss-custom-properties_v8.0.10/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-custom-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-custom-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-custom-properties/index' {
  declare module.exports: $Exports<'postcss-custom-properties'>;
}
declare module 'postcss-custom-properties/index.js' {
  declare module.exports: $Exports<'postcss-custom-properties'>;
}
