// flow-typed signature: 5a94113f7d92e474a9efd2edf430f2c2
// flow-typed version: <<STUB>>/preact-render-to-string_v5.0.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-render-to-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-render-to-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-render-to-string/dist/index' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/dist/index.module' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/dist/jsx' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/dist/jsx.module' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/jsx' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/index' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/jsx' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/polyfills' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-render-to-string/dist/index.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist/index'>;
}
declare module 'preact-render-to-string/dist/index.module.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist/index.module'>;
}
declare module 'preact-render-to-string/dist/jsx.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist/jsx'>;
}
declare module 'preact-render-to-string/dist/jsx.module.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist/jsx.module'>;
}
declare module 'preact-render-to-string/jsx.js' {
  declare module.exports: $Exports<'preact-render-to-string/jsx'>;
}
declare module 'preact-render-to-string/src/index.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/index'>;
}
declare module 'preact-render-to-string/src/jsx.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/jsx'>;
}
declare module 'preact-render-to-string/src/polyfills.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/polyfills'>;
}
declare module 'preact-render-to-string/src/util.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/util'>;
}
