// flow-typed signature: 31b720e7b25f9499e4a853ba46e4deed
// flow-typed version: <<STUB>>/prepack_v0.2.40/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prepack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prepack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prepack/bin/prepack-repl' {
  declare module.exports: any;
}

declare module 'prepack/bin/prepack' {
  declare module.exports: any;
}

declare module 'prepack/lib/benchmarker' {
  declare module.exports: any;
}

declare module 'prepack/lib/completions' {
  declare module.exports: any;
}

declare module 'prepack/lib/construct_realm' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/adapter/channel/AdapterChannel' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/adapter/DebugAdapter' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/common/channel/DebugMessage' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/common/channel/FileIOWrapper' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/common/channel/MessageMarshaller' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/common/channel/MessagePackager' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/common/DebuggerConstants' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/common/DebuggerError' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/common/invariant' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/common/types' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/mock-ui/DataHandler' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/mock-ui/debugger-cli' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/mock-ui/UISession' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/server/Breakpoint' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/server/BreakpointManager' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/server/channel/DebugChannel' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/server/Debugger' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/server/PerFileBreakpointMap' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/server/ReferenceMap' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/server/Stepper' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/server/SteppingManager' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/server/StopEventManager' {
  declare module.exports: any;
}

declare module 'prepack/lib/debugger/server/VariableManager' {
  declare module.exports: any;
}

declare module 'prepack/lib/domains/index' {
  declare module.exports: any;
}

declare module 'prepack/lib/domains/TypesDomain' {
  declare module.exports: any;
}

declare module 'prepack/lib/domains/ValuesDomain' {
  declare module.exports: any;
}

declare module 'prepack/lib/environment' {
  declare module.exports: any;
}

declare module 'prepack/lib/errors' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ArrayExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ArrowFunctionExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/AssignmentExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/AwaitExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/BinaryExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/BlockStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/BooleanLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/BreakStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/CallExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/CatchClause' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ClassDeclaration' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ClassExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ConditionalExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ContinueStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/Directive' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/DirectiveLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/DoExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/DoWhileStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/EmptyStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ExpressionStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/File' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ForInStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ForOfStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ForStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/FunctionDeclaration' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/FunctionExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/Identifier' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/IfStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/index' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/JSXElement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/LabeledStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/LogicalExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/MemberExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/MetaProperty' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/NewExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/NullLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/NumericLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ObjectExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/Program' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/RegExpLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ReturnStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/SequenceExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/StringLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/SuperCall' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/SuperProperty' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/SwitchStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/TaggedTemplateExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/TemplateLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ThisExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/ThrowStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/TryStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/UnaryExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/UpdateExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/VariableDeclaration' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/WhileStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/WithStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/evaluators/YieldExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/globals' {
  declare module.exports: any;
}

declare module 'prepack/lib/initialize-singletons' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/common/console' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/dom/document' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/dom/global' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/dom/setInterval' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/dom/setTimeout' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Array' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ArrayBuffer' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ArrayBufferPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ArrayIteratorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ArrayProto_toString' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ArrayProto_values' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Boolean' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/BooleanPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/DataView' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/DataViewPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Date' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/DatePrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/decodeURI' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/decodeURIComponent' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/encodeURI' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/encodeURIComponent' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Error' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ErrorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/eval' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/EvalError' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/EvalErrorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Float32Array' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Float32ArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Float64Array' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Float64ArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Function' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/FunctionPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Generator' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/GeneratorFunction' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/GeneratorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/global' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Int16Array' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Int16ArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Int32Array' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Int32ArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Int8Array' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Int8ArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/isFinite' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/isNaN' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/IteratorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/JSON' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Map' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/MapIteratorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/MapPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Math' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Number' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/NumberPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Object' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ObjectProto_toString' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ObjectPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/parseFloat' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/parseInt' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Promise' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/PromisePrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Proxy' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/RangeError' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/RangeErrorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ReferenceError' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ReferenceErrorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Reflect' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/RegExp' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/RegExpPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Set' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/SetIteratorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/SetPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/String' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/StringIteratorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/StringPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Symbol' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/SymbolPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/SyntaxError' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/SyntaxErrorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/ThrowTypeError' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/TypedArray' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/TypedArrayProto_values' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/TypedArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/TypeError' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/TypeErrorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Uint16Array' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Uint16ArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Uint32Array' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Uint32ArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Uint8Array' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Uint8ArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Uint8ClampedArray' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/Uint8ClampedArrayPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/URIError' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/URIErrorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/WeakMap' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/WeakMapPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/WeakSet' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/ecma262/WeakSetPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/fb-www/fb-mocks' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/fb-www/global' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/fb-www/react-mocks' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/fb-www/relay-mocks' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/fb-www/utils' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/index' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/node/bootstrap' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/node/buffer' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/node/contextify' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/node/fs' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/node/process' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/node/utils' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/prepack/__IntrospectionError' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/prepack/__IntrospectionErrorPrototype' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/prepack/global' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/prepack/utils' {
  declare module.exports: any;
}

declare module 'prepack/lib/intrinsics/react-native/global' {
  declare module.exports: any;
}

declare module 'prepack/lib/invariant' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/abstract' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/arraybuffer' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/call' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/construct' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/create' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/date' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/descriptor' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/destructuring' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/environment' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/function' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/generator' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/get' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/has' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/hash' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/index' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/integerindexed' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/integrity' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/is' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/iterator' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/join' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/json' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/own' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/promise' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/properties' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/proxy' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/regexp' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/to' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/typedarray' {
  declare module.exports: any;
}

declare module 'prepack/lib/methods/widen' {
  declare module.exports: any;
}

declare module 'prepack/lib/options' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ArrayExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ArrowFunctionExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/AssignmentExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/AwaitExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/BinaryExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/BlockStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/BooleanLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/BreakStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/CallExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/CatchClause' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ClassDeclaration' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ClassExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ConditionalExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ContinueStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/Directive' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/DirectiveLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/DoExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/DoWhileStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/EmptyStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ExpressionStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/File' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ForInStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ForOfStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ForStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/FunctionDeclaration' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/FunctionExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/Identifier' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/IfStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/index' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/LabeledStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/LogicalExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/MemberExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/MetaProperty' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/NewExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/NullLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/NumericLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ObjectExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/Program' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/RegExpLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ReturnStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/SequenceExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/StringLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/SwitchStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/TaggedTemplateExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/TemplateLiteral' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ThisExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/ThrowStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/TryStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/UnaryExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/UpdateExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/VariableDeclaration' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/WhileStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/WithStatement' {
  declare module.exports: any;
}

declare module 'prepack/lib/partial-evaluators/YieldExpression' {
  declare module.exports: any;
}

declare module 'prepack/lib/prepack-cli' {
  declare module.exports: any;
}

declare module 'prepack/lib/prepack-node-environment' {
  declare module.exports: any;
}

declare module 'prepack/lib/prepack-node' {
  declare module.exports: any;
}

declare module 'prepack/lib/prepack-options' {
  declare module.exports: any;
}

declare module 'prepack/lib/prepack-standalone' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/branching' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/components' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/elements' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/errors' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/experimental-server-rendering/dom-config' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/experimental-server-rendering/rendering' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/experimental-server-rendering/utils' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/hoisting' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/jsx' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/optimizing' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/ReactElementSet' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/ReactEquivalenceSet' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/ReactPropsSet' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/reconcilation' {
  declare module.exports: any;
}

declare module 'prepack/lib/react/utils' {
  declare module.exports: any;
}

declare module 'prepack/lib/realm' {
  declare module.exports: any;
}

declare module 'prepack/lib/repl-cli' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/Emitter' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/factorify' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/functions' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/GeneratorDAG' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/index' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/LazyObjectsSerializer' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/LoggingTracer' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/Referentializer' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/ResidualFunctionInitializers' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/ResidualFunctionInstantiator' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/ResidualFunctions' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/ResidualHeapGraphGenerator' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/ResidualHeapRefCounter' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/ResidualHeapSerializer' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/ResidualHeapValueIdentifiers' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/ResidualHeapVisitor' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/ResidualReactElementSerializer' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/ResidualReactElementVisitor' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/serializer' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/statistics' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/types' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/utils' {
  declare module.exports: any;
}

declare module 'prepack/lib/serializer/visitors' {
  declare module.exports: any;
}

declare module 'prepack/lib/singletons' {
  declare module.exports: any;
}

declare module 'prepack/lib/statistics' {
  declare module.exports: any;
}

declare module 'prepack/lib/types' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/builder' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/ConcreteModelConverter' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/errors' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/flow' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/generator' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/havoc' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/HeapInspector' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/internalizer' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/json' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/JSONTokenizer' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/logger' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/modules' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/native-to-interp' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/parse' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/paths' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/simplifier' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/strict' {
  declare module.exports: any;
}

declare module 'prepack/lib/utils/traverse-fast' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/AbstractObjectValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/AbstractValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/ArgumentsExotic' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/ArrayValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/BooleanValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/BoundFunctionValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/ConcreteValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/ECMAScriptFunctionValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/ECMAScriptSourceFunctionValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/EmptyValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/FunctionValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/index' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/IntegerIndexedExotic' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/NativeFunctionValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/NullValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/NumberValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/ObjectValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/PrimitiveValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/ProxyValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/StringExotic' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/StringValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/SymbolValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/UndefinedValue' {
  declare module.exports: any;
}

declare module 'prepack/lib/values/Value' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prepack/bin/prepack-repl.js' {
  declare module.exports: $Exports<'prepack/bin/prepack-repl'>;
}
declare module 'prepack/bin/prepack.js' {
  declare module.exports: $Exports<'prepack/bin/prepack'>;
}
declare module 'prepack/lib/benchmarker.js' {
  declare module.exports: $Exports<'prepack/lib/benchmarker'>;
}
declare module 'prepack/lib/completions.js' {
  declare module.exports: $Exports<'prepack/lib/completions'>;
}
declare module 'prepack/lib/construct_realm.js' {
  declare module.exports: $Exports<'prepack/lib/construct_realm'>;
}
declare module 'prepack/lib/debugger/adapter/channel/AdapterChannel.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/adapter/channel/AdapterChannel'>;
}
declare module 'prepack/lib/debugger/adapter/DebugAdapter.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/adapter/DebugAdapter'>;
}
declare module 'prepack/lib/debugger/common/channel/DebugMessage.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/common/channel/DebugMessage'>;
}
declare module 'prepack/lib/debugger/common/channel/FileIOWrapper.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/common/channel/FileIOWrapper'>;
}
declare module 'prepack/lib/debugger/common/channel/MessageMarshaller.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/common/channel/MessageMarshaller'>;
}
declare module 'prepack/lib/debugger/common/channel/MessagePackager.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/common/channel/MessagePackager'>;
}
declare module 'prepack/lib/debugger/common/DebuggerConstants.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/common/DebuggerConstants'>;
}
declare module 'prepack/lib/debugger/common/DebuggerError.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/common/DebuggerError'>;
}
declare module 'prepack/lib/debugger/common/invariant.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/common/invariant'>;
}
declare module 'prepack/lib/debugger/common/types.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/common/types'>;
}
declare module 'prepack/lib/debugger/mock-ui/DataHandler.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/mock-ui/DataHandler'>;
}
declare module 'prepack/lib/debugger/mock-ui/debugger-cli.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/mock-ui/debugger-cli'>;
}
declare module 'prepack/lib/debugger/mock-ui/UISession.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/mock-ui/UISession'>;
}
declare module 'prepack/lib/debugger/server/Breakpoint.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/server/Breakpoint'>;
}
declare module 'prepack/lib/debugger/server/BreakpointManager.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/server/BreakpointManager'>;
}
declare module 'prepack/lib/debugger/server/channel/DebugChannel.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/server/channel/DebugChannel'>;
}
declare module 'prepack/lib/debugger/server/Debugger.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/server/Debugger'>;
}
declare module 'prepack/lib/debugger/server/PerFileBreakpointMap.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/server/PerFileBreakpointMap'>;
}
declare module 'prepack/lib/debugger/server/ReferenceMap.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/server/ReferenceMap'>;
}
declare module 'prepack/lib/debugger/server/Stepper.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/server/Stepper'>;
}
declare module 'prepack/lib/debugger/server/SteppingManager.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/server/SteppingManager'>;
}
declare module 'prepack/lib/debugger/server/StopEventManager.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/server/StopEventManager'>;
}
declare module 'prepack/lib/debugger/server/VariableManager.js' {
  declare module.exports: $Exports<'prepack/lib/debugger/server/VariableManager'>;
}
declare module 'prepack/lib/domains/index.js' {
  declare module.exports: $Exports<'prepack/lib/domains/index'>;
}
declare module 'prepack/lib/domains/TypesDomain.js' {
  declare module.exports: $Exports<'prepack/lib/domains/TypesDomain'>;
}
declare module 'prepack/lib/domains/ValuesDomain.js' {
  declare module.exports: $Exports<'prepack/lib/domains/ValuesDomain'>;
}
declare module 'prepack/lib/environment.js' {
  declare module.exports: $Exports<'prepack/lib/environment'>;
}
declare module 'prepack/lib/errors.js' {
  declare module.exports: $Exports<'prepack/lib/errors'>;
}
declare module 'prepack/lib/evaluators/ArrayExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ArrayExpression'>;
}
declare module 'prepack/lib/evaluators/ArrowFunctionExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ArrowFunctionExpression'>;
}
declare module 'prepack/lib/evaluators/AssignmentExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/AssignmentExpression'>;
}
declare module 'prepack/lib/evaluators/AwaitExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/AwaitExpression'>;
}
declare module 'prepack/lib/evaluators/BinaryExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/BinaryExpression'>;
}
declare module 'prepack/lib/evaluators/BlockStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/BlockStatement'>;
}
declare module 'prepack/lib/evaluators/BooleanLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/BooleanLiteral'>;
}
declare module 'prepack/lib/evaluators/BreakStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/BreakStatement'>;
}
declare module 'prepack/lib/evaluators/CallExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/CallExpression'>;
}
declare module 'prepack/lib/evaluators/CatchClause.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/CatchClause'>;
}
declare module 'prepack/lib/evaluators/ClassDeclaration.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ClassDeclaration'>;
}
declare module 'prepack/lib/evaluators/ClassExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ClassExpression'>;
}
declare module 'prepack/lib/evaluators/ConditionalExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ConditionalExpression'>;
}
declare module 'prepack/lib/evaluators/ContinueStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ContinueStatement'>;
}
declare module 'prepack/lib/evaluators/Directive.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/Directive'>;
}
declare module 'prepack/lib/evaluators/DirectiveLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/DirectiveLiteral'>;
}
declare module 'prepack/lib/evaluators/DoExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/DoExpression'>;
}
declare module 'prepack/lib/evaluators/DoWhileStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/DoWhileStatement'>;
}
declare module 'prepack/lib/evaluators/EmptyStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/EmptyStatement'>;
}
declare module 'prepack/lib/evaluators/ExpressionStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ExpressionStatement'>;
}
declare module 'prepack/lib/evaluators/File.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/File'>;
}
declare module 'prepack/lib/evaluators/ForInStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ForInStatement'>;
}
declare module 'prepack/lib/evaluators/ForOfStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ForOfStatement'>;
}
declare module 'prepack/lib/evaluators/ForStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ForStatement'>;
}
declare module 'prepack/lib/evaluators/FunctionDeclaration.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/FunctionDeclaration'>;
}
declare module 'prepack/lib/evaluators/FunctionExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/FunctionExpression'>;
}
declare module 'prepack/lib/evaluators/Identifier.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/Identifier'>;
}
declare module 'prepack/lib/evaluators/IfStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/IfStatement'>;
}
declare module 'prepack/lib/evaluators/index.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/index'>;
}
declare module 'prepack/lib/evaluators/JSXElement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/JSXElement'>;
}
declare module 'prepack/lib/evaluators/LabeledStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/LabeledStatement'>;
}
declare module 'prepack/lib/evaluators/LogicalExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/LogicalExpression'>;
}
declare module 'prepack/lib/evaluators/MemberExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/MemberExpression'>;
}
declare module 'prepack/lib/evaluators/MetaProperty.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/MetaProperty'>;
}
declare module 'prepack/lib/evaluators/NewExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/NewExpression'>;
}
declare module 'prepack/lib/evaluators/NullLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/NullLiteral'>;
}
declare module 'prepack/lib/evaluators/NumericLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/NumericLiteral'>;
}
declare module 'prepack/lib/evaluators/ObjectExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ObjectExpression'>;
}
declare module 'prepack/lib/evaluators/Program.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/Program'>;
}
declare module 'prepack/lib/evaluators/RegExpLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/RegExpLiteral'>;
}
declare module 'prepack/lib/evaluators/ReturnStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ReturnStatement'>;
}
declare module 'prepack/lib/evaluators/SequenceExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/SequenceExpression'>;
}
declare module 'prepack/lib/evaluators/StringLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/StringLiteral'>;
}
declare module 'prepack/lib/evaluators/SuperCall.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/SuperCall'>;
}
declare module 'prepack/lib/evaluators/SuperProperty.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/SuperProperty'>;
}
declare module 'prepack/lib/evaluators/SwitchStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/SwitchStatement'>;
}
declare module 'prepack/lib/evaluators/TaggedTemplateExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/TaggedTemplateExpression'>;
}
declare module 'prepack/lib/evaluators/TemplateLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/TemplateLiteral'>;
}
declare module 'prepack/lib/evaluators/ThisExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ThisExpression'>;
}
declare module 'prepack/lib/evaluators/ThrowStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/ThrowStatement'>;
}
declare module 'prepack/lib/evaluators/TryStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/TryStatement'>;
}
declare module 'prepack/lib/evaluators/UnaryExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/UnaryExpression'>;
}
declare module 'prepack/lib/evaluators/UpdateExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/UpdateExpression'>;
}
declare module 'prepack/lib/evaluators/VariableDeclaration.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/VariableDeclaration'>;
}
declare module 'prepack/lib/evaluators/WhileStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/WhileStatement'>;
}
declare module 'prepack/lib/evaluators/WithStatement.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/WithStatement'>;
}
declare module 'prepack/lib/evaluators/YieldExpression.js' {
  declare module.exports: $Exports<'prepack/lib/evaluators/YieldExpression'>;
}
declare module 'prepack/lib/globals.js' {
  declare module.exports: $Exports<'prepack/lib/globals'>;
}
declare module 'prepack/lib/initialize-singletons.js' {
  declare module.exports: $Exports<'prepack/lib/initialize-singletons'>;
}
declare module 'prepack/lib/intrinsics/common/console.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/common/console'>;
}
declare module 'prepack/lib/intrinsics/dom/document.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/dom/document'>;
}
declare module 'prepack/lib/intrinsics/dom/global.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/dom/global'>;
}
declare module 'prepack/lib/intrinsics/dom/setInterval.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/dom/setInterval'>;
}
declare module 'prepack/lib/intrinsics/dom/setTimeout.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/dom/setTimeout'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Array.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Array'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ArrayBuffer.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ArrayBuffer'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ArrayBufferPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ArrayBufferPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ArrayIteratorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ArrayIteratorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ArrayProto_toString.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ArrayProto_toString'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ArrayProto_values.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ArrayProto_values'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Boolean.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Boolean'>;
}
declare module 'prepack/lib/intrinsics/ecma262/BooleanPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/BooleanPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/DataView.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/DataView'>;
}
declare module 'prepack/lib/intrinsics/ecma262/DataViewPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/DataViewPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Date.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Date'>;
}
declare module 'prepack/lib/intrinsics/ecma262/DatePrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/DatePrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/decodeURI.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/decodeURI'>;
}
declare module 'prepack/lib/intrinsics/ecma262/decodeURIComponent.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/decodeURIComponent'>;
}
declare module 'prepack/lib/intrinsics/ecma262/encodeURI.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/encodeURI'>;
}
declare module 'prepack/lib/intrinsics/ecma262/encodeURIComponent.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/encodeURIComponent'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Error.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Error'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ErrorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ErrorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/eval.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/eval'>;
}
declare module 'prepack/lib/intrinsics/ecma262/EvalError.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/EvalError'>;
}
declare module 'prepack/lib/intrinsics/ecma262/EvalErrorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/EvalErrorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Float32Array.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Float32Array'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Float32ArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Float32ArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Float64Array.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Float64Array'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Float64ArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Float64ArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Function.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Function'>;
}
declare module 'prepack/lib/intrinsics/ecma262/FunctionPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/FunctionPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Generator.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Generator'>;
}
declare module 'prepack/lib/intrinsics/ecma262/GeneratorFunction.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/GeneratorFunction'>;
}
declare module 'prepack/lib/intrinsics/ecma262/GeneratorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/GeneratorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/global.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/global'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Int16Array.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Int16Array'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Int16ArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Int16ArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Int32Array.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Int32Array'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Int32ArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Int32ArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Int8Array.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Int8Array'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Int8ArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Int8ArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/isFinite.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/isFinite'>;
}
declare module 'prepack/lib/intrinsics/ecma262/isNaN.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/isNaN'>;
}
declare module 'prepack/lib/intrinsics/ecma262/IteratorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/IteratorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/JSON.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/JSON'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Map.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Map'>;
}
declare module 'prepack/lib/intrinsics/ecma262/MapIteratorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/MapIteratorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/MapPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/MapPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Math.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Math'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Number.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Number'>;
}
declare module 'prepack/lib/intrinsics/ecma262/NumberPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/NumberPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Object.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Object'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ObjectProto_toString.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ObjectProto_toString'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ObjectPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ObjectPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/parseFloat.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/parseFloat'>;
}
declare module 'prepack/lib/intrinsics/ecma262/parseInt.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/parseInt'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Promise.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Promise'>;
}
declare module 'prepack/lib/intrinsics/ecma262/PromisePrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/PromisePrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Proxy.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Proxy'>;
}
declare module 'prepack/lib/intrinsics/ecma262/RangeError.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/RangeError'>;
}
declare module 'prepack/lib/intrinsics/ecma262/RangeErrorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/RangeErrorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ReferenceError.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ReferenceError'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ReferenceErrorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ReferenceErrorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Reflect.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Reflect'>;
}
declare module 'prepack/lib/intrinsics/ecma262/RegExp.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/RegExp'>;
}
declare module 'prepack/lib/intrinsics/ecma262/RegExpPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/RegExpPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Set.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Set'>;
}
declare module 'prepack/lib/intrinsics/ecma262/SetIteratorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/SetIteratorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/SetPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/SetPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/String.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/String'>;
}
declare module 'prepack/lib/intrinsics/ecma262/StringIteratorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/StringIteratorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/StringPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/StringPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Symbol.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Symbol'>;
}
declare module 'prepack/lib/intrinsics/ecma262/SymbolPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/SymbolPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/SyntaxError.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/SyntaxError'>;
}
declare module 'prepack/lib/intrinsics/ecma262/SyntaxErrorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/SyntaxErrorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/ThrowTypeError.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/ThrowTypeError'>;
}
declare module 'prepack/lib/intrinsics/ecma262/TypedArray.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/TypedArray'>;
}
declare module 'prepack/lib/intrinsics/ecma262/TypedArrayProto_values.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/TypedArrayProto_values'>;
}
declare module 'prepack/lib/intrinsics/ecma262/TypedArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/TypedArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/TypeError.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/TypeError'>;
}
declare module 'prepack/lib/intrinsics/ecma262/TypeErrorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/TypeErrorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Uint16Array.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Uint16Array'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Uint16ArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Uint16ArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Uint32Array.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Uint32Array'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Uint32ArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Uint32ArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Uint8Array.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Uint8Array'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Uint8ArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Uint8ArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Uint8ClampedArray.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Uint8ClampedArray'>;
}
declare module 'prepack/lib/intrinsics/ecma262/Uint8ClampedArrayPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/Uint8ClampedArrayPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/URIError.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/URIError'>;
}
declare module 'prepack/lib/intrinsics/ecma262/URIErrorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/URIErrorPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/WeakMap.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/WeakMap'>;
}
declare module 'prepack/lib/intrinsics/ecma262/WeakMapPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/WeakMapPrototype'>;
}
declare module 'prepack/lib/intrinsics/ecma262/WeakSet.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/WeakSet'>;
}
declare module 'prepack/lib/intrinsics/ecma262/WeakSetPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/ecma262/WeakSetPrototype'>;
}
declare module 'prepack/lib/intrinsics/fb-www/fb-mocks.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/fb-www/fb-mocks'>;
}
declare module 'prepack/lib/intrinsics/fb-www/global.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/fb-www/global'>;
}
declare module 'prepack/lib/intrinsics/fb-www/react-mocks.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/fb-www/react-mocks'>;
}
declare module 'prepack/lib/intrinsics/fb-www/relay-mocks.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/fb-www/relay-mocks'>;
}
declare module 'prepack/lib/intrinsics/fb-www/utils.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/fb-www/utils'>;
}
declare module 'prepack/lib/intrinsics/index.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/index'>;
}
declare module 'prepack/lib/intrinsics/node/bootstrap.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/node/bootstrap'>;
}
declare module 'prepack/lib/intrinsics/node/buffer.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/node/buffer'>;
}
declare module 'prepack/lib/intrinsics/node/contextify.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/node/contextify'>;
}
declare module 'prepack/lib/intrinsics/node/fs.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/node/fs'>;
}
declare module 'prepack/lib/intrinsics/node/process.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/node/process'>;
}
declare module 'prepack/lib/intrinsics/node/utils.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/node/utils'>;
}
declare module 'prepack/lib/intrinsics/prepack/__IntrospectionError.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/prepack/__IntrospectionError'>;
}
declare module 'prepack/lib/intrinsics/prepack/__IntrospectionErrorPrototype.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/prepack/__IntrospectionErrorPrototype'>;
}
declare module 'prepack/lib/intrinsics/prepack/global.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/prepack/global'>;
}
declare module 'prepack/lib/intrinsics/prepack/utils.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/prepack/utils'>;
}
declare module 'prepack/lib/intrinsics/react-native/global.js' {
  declare module.exports: $Exports<'prepack/lib/intrinsics/react-native/global'>;
}
declare module 'prepack/lib/invariant.js' {
  declare module.exports: $Exports<'prepack/lib/invariant'>;
}
declare module 'prepack/lib/methods/abstract.js' {
  declare module.exports: $Exports<'prepack/lib/methods/abstract'>;
}
declare module 'prepack/lib/methods/arraybuffer.js' {
  declare module.exports: $Exports<'prepack/lib/methods/arraybuffer'>;
}
declare module 'prepack/lib/methods/call.js' {
  declare module.exports: $Exports<'prepack/lib/methods/call'>;
}
declare module 'prepack/lib/methods/construct.js' {
  declare module.exports: $Exports<'prepack/lib/methods/construct'>;
}
declare module 'prepack/lib/methods/create.js' {
  declare module.exports: $Exports<'prepack/lib/methods/create'>;
}
declare module 'prepack/lib/methods/date.js' {
  declare module.exports: $Exports<'prepack/lib/methods/date'>;
}
declare module 'prepack/lib/methods/descriptor.js' {
  declare module.exports: $Exports<'prepack/lib/methods/descriptor'>;
}
declare module 'prepack/lib/methods/destructuring.js' {
  declare module.exports: $Exports<'prepack/lib/methods/destructuring'>;
}
declare module 'prepack/lib/methods/environment.js' {
  declare module.exports: $Exports<'prepack/lib/methods/environment'>;
}
declare module 'prepack/lib/methods/function.js' {
  declare module.exports: $Exports<'prepack/lib/methods/function'>;
}
declare module 'prepack/lib/methods/generator.js' {
  declare module.exports: $Exports<'prepack/lib/methods/generator'>;
}
declare module 'prepack/lib/methods/get.js' {
  declare module.exports: $Exports<'prepack/lib/methods/get'>;
}
declare module 'prepack/lib/methods/has.js' {
  declare module.exports: $Exports<'prepack/lib/methods/has'>;
}
declare module 'prepack/lib/methods/hash.js' {
  declare module.exports: $Exports<'prepack/lib/methods/hash'>;
}
declare module 'prepack/lib/methods/index.js' {
  declare module.exports: $Exports<'prepack/lib/methods/index'>;
}
declare module 'prepack/lib/methods/integerindexed.js' {
  declare module.exports: $Exports<'prepack/lib/methods/integerindexed'>;
}
declare module 'prepack/lib/methods/integrity.js' {
  declare module.exports: $Exports<'prepack/lib/methods/integrity'>;
}
declare module 'prepack/lib/methods/is.js' {
  declare module.exports: $Exports<'prepack/lib/methods/is'>;
}
declare module 'prepack/lib/methods/iterator.js' {
  declare module.exports: $Exports<'prepack/lib/methods/iterator'>;
}
declare module 'prepack/lib/methods/join.js' {
  declare module.exports: $Exports<'prepack/lib/methods/join'>;
}
declare module 'prepack/lib/methods/json.js' {
  declare module.exports: $Exports<'prepack/lib/methods/json'>;
}
declare module 'prepack/lib/methods/own.js' {
  declare module.exports: $Exports<'prepack/lib/methods/own'>;
}
declare module 'prepack/lib/methods/promise.js' {
  declare module.exports: $Exports<'prepack/lib/methods/promise'>;
}
declare module 'prepack/lib/methods/properties.js' {
  declare module.exports: $Exports<'prepack/lib/methods/properties'>;
}
declare module 'prepack/lib/methods/proxy.js' {
  declare module.exports: $Exports<'prepack/lib/methods/proxy'>;
}
declare module 'prepack/lib/methods/regexp.js' {
  declare module.exports: $Exports<'prepack/lib/methods/regexp'>;
}
declare module 'prepack/lib/methods/to.js' {
  declare module.exports: $Exports<'prepack/lib/methods/to'>;
}
declare module 'prepack/lib/methods/typedarray.js' {
  declare module.exports: $Exports<'prepack/lib/methods/typedarray'>;
}
declare module 'prepack/lib/methods/widen.js' {
  declare module.exports: $Exports<'prepack/lib/methods/widen'>;
}
declare module 'prepack/lib/options.js' {
  declare module.exports: $Exports<'prepack/lib/options'>;
}
declare module 'prepack/lib/partial-evaluators/ArrayExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ArrayExpression'>;
}
declare module 'prepack/lib/partial-evaluators/ArrowFunctionExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ArrowFunctionExpression'>;
}
declare module 'prepack/lib/partial-evaluators/AssignmentExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/AssignmentExpression'>;
}
declare module 'prepack/lib/partial-evaluators/AwaitExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/AwaitExpression'>;
}
declare module 'prepack/lib/partial-evaluators/BinaryExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/BinaryExpression'>;
}
declare module 'prepack/lib/partial-evaluators/BlockStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/BlockStatement'>;
}
declare module 'prepack/lib/partial-evaluators/BooleanLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/BooleanLiteral'>;
}
declare module 'prepack/lib/partial-evaluators/BreakStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/BreakStatement'>;
}
declare module 'prepack/lib/partial-evaluators/CallExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/CallExpression'>;
}
declare module 'prepack/lib/partial-evaluators/CatchClause.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/CatchClause'>;
}
declare module 'prepack/lib/partial-evaluators/ClassDeclaration.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ClassDeclaration'>;
}
declare module 'prepack/lib/partial-evaluators/ClassExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ClassExpression'>;
}
declare module 'prepack/lib/partial-evaluators/ConditionalExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ConditionalExpression'>;
}
declare module 'prepack/lib/partial-evaluators/ContinueStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ContinueStatement'>;
}
declare module 'prepack/lib/partial-evaluators/Directive.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/Directive'>;
}
declare module 'prepack/lib/partial-evaluators/DirectiveLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/DirectiveLiteral'>;
}
declare module 'prepack/lib/partial-evaluators/DoExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/DoExpression'>;
}
declare module 'prepack/lib/partial-evaluators/DoWhileStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/DoWhileStatement'>;
}
declare module 'prepack/lib/partial-evaluators/EmptyStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/EmptyStatement'>;
}
declare module 'prepack/lib/partial-evaluators/ExpressionStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ExpressionStatement'>;
}
declare module 'prepack/lib/partial-evaluators/File.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/File'>;
}
declare module 'prepack/lib/partial-evaluators/ForInStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ForInStatement'>;
}
declare module 'prepack/lib/partial-evaluators/ForOfStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ForOfStatement'>;
}
declare module 'prepack/lib/partial-evaluators/ForStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ForStatement'>;
}
declare module 'prepack/lib/partial-evaluators/FunctionDeclaration.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/FunctionDeclaration'>;
}
declare module 'prepack/lib/partial-evaluators/FunctionExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/FunctionExpression'>;
}
declare module 'prepack/lib/partial-evaluators/Identifier.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/Identifier'>;
}
declare module 'prepack/lib/partial-evaluators/IfStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/IfStatement'>;
}
declare module 'prepack/lib/partial-evaluators/index.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/index'>;
}
declare module 'prepack/lib/partial-evaluators/LabeledStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/LabeledStatement'>;
}
declare module 'prepack/lib/partial-evaluators/LogicalExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/LogicalExpression'>;
}
declare module 'prepack/lib/partial-evaluators/MemberExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/MemberExpression'>;
}
declare module 'prepack/lib/partial-evaluators/MetaProperty.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/MetaProperty'>;
}
declare module 'prepack/lib/partial-evaluators/NewExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/NewExpression'>;
}
declare module 'prepack/lib/partial-evaluators/NullLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/NullLiteral'>;
}
declare module 'prepack/lib/partial-evaluators/NumericLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/NumericLiteral'>;
}
declare module 'prepack/lib/partial-evaluators/ObjectExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ObjectExpression'>;
}
declare module 'prepack/lib/partial-evaluators/Program.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/Program'>;
}
declare module 'prepack/lib/partial-evaluators/RegExpLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/RegExpLiteral'>;
}
declare module 'prepack/lib/partial-evaluators/ReturnStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ReturnStatement'>;
}
declare module 'prepack/lib/partial-evaluators/SequenceExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/SequenceExpression'>;
}
declare module 'prepack/lib/partial-evaluators/StringLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/StringLiteral'>;
}
declare module 'prepack/lib/partial-evaluators/SwitchStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/SwitchStatement'>;
}
declare module 'prepack/lib/partial-evaluators/TaggedTemplateExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/TaggedTemplateExpression'>;
}
declare module 'prepack/lib/partial-evaluators/TemplateLiteral.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/TemplateLiteral'>;
}
declare module 'prepack/lib/partial-evaluators/ThisExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ThisExpression'>;
}
declare module 'prepack/lib/partial-evaluators/ThrowStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/ThrowStatement'>;
}
declare module 'prepack/lib/partial-evaluators/TryStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/TryStatement'>;
}
declare module 'prepack/lib/partial-evaluators/UnaryExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/UnaryExpression'>;
}
declare module 'prepack/lib/partial-evaluators/UpdateExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/UpdateExpression'>;
}
declare module 'prepack/lib/partial-evaluators/VariableDeclaration.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/VariableDeclaration'>;
}
declare module 'prepack/lib/partial-evaluators/WhileStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/WhileStatement'>;
}
declare module 'prepack/lib/partial-evaluators/WithStatement.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/WithStatement'>;
}
declare module 'prepack/lib/partial-evaluators/YieldExpression.js' {
  declare module.exports: $Exports<'prepack/lib/partial-evaluators/YieldExpression'>;
}
declare module 'prepack/lib/prepack-cli.js' {
  declare module.exports: $Exports<'prepack/lib/prepack-cli'>;
}
declare module 'prepack/lib/prepack-node-environment.js' {
  declare module.exports: $Exports<'prepack/lib/prepack-node-environment'>;
}
declare module 'prepack/lib/prepack-node.js' {
  declare module.exports: $Exports<'prepack/lib/prepack-node'>;
}
declare module 'prepack/lib/prepack-options.js' {
  declare module.exports: $Exports<'prepack/lib/prepack-options'>;
}
declare module 'prepack/lib/prepack-standalone.js' {
  declare module.exports: $Exports<'prepack/lib/prepack-standalone'>;
}
declare module 'prepack/lib/react/branching.js' {
  declare module.exports: $Exports<'prepack/lib/react/branching'>;
}
declare module 'prepack/lib/react/components.js' {
  declare module.exports: $Exports<'prepack/lib/react/components'>;
}
declare module 'prepack/lib/react/elements.js' {
  declare module.exports: $Exports<'prepack/lib/react/elements'>;
}
declare module 'prepack/lib/react/errors.js' {
  declare module.exports: $Exports<'prepack/lib/react/errors'>;
}
declare module 'prepack/lib/react/experimental-server-rendering/dom-config.js' {
  declare module.exports: $Exports<'prepack/lib/react/experimental-server-rendering/dom-config'>;
}
declare module 'prepack/lib/react/experimental-server-rendering/rendering.js' {
  declare module.exports: $Exports<'prepack/lib/react/experimental-server-rendering/rendering'>;
}
declare module 'prepack/lib/react/experimental-server-rendering/utils.js' {
  declare module.exports: $Exports<'prepack/lib/react/experimental-server-rendering/utils'>;
}
declare module 'prepack/lib/react/hoisting.js' {
  declare module.exports: $Exports<'prepack/lib/react/hoisting'>;
}
declare module 'prepack/lib/react/jsx.js' {
  declare module.exports: $Exports<'prepack/lib/react/jsx'>;
}
declare module 'prepack/lib/react/optimizing.js' {
  declare module.exports: $Exports<'prepack/lib/react/optimizing'>;
}
declare module 'prepack/lib/react/ReactElementSet.js' {
  declare module.exports: $Exports<'prepack/lib/react/ReactElementSet'>;
}
declare module 'prepack/lib/react/ReactEquivalenceSet.js' {
  declare module.exports: $Exports<'prepack/lib/react/ReactEquivalenceSet'>;
}
declare module 'prepack/lib/react/ReactPropsSet.js' {
  declare module.exports: $Exports<'prepack/lib/react/ReactPropsSet'>;
}
declare module 'prepack/lib/react/reconcilation.js' {
  declare module.exports: $Exports<'prepack/lib/react/reconcilation'>;
}
declare module 'prepack/lib/react/utils.js' {
  declare module.exports: $Exports<'prepack/lib/react/utils'>;
}
declare module 'prepack/lib/realm.js' {
  declare module.exports: $Exports<'prepack/lib/realm'>;
}
declare module 'prepack/lib/repl-cli.js' {
  declare module.exports: $Exports<'prepack/lib/repl-cli'>;
}
declare module 'prepack/lib/serializer/Emitter.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/Emitter'>;
}
declare module 'prepack/lib/serializer/factorify.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/factorify'>;
}
declare module 'prepack/lib/serializer/functions.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/functions'>;
}
declare module 'prepack/lib/serializer/GeneratorDAG.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/GeneratorDAG'>;
}
declare module 'prepack/lib/serializer/index.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/index'>;
}
declare module 'prepack/lib/serializer/LazyObjectsSerializer.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/LazyObjectsSerializer'>;
}
declare module 'prepack/lib/serializer/LoggingTracer.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/LoggingTracer'>;
}
declare module 'prepack/lib/serializer/Referentializer.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/Referentializer'>;
}
declare module 'prepack/lib/serializer/ResidualFunctionInitializers.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/ResidualFunctionInitializers'>;
}
declare module 'prepack/lib/serializer/ResidualFunctionInstantiator.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/ResidualFunctionInstantiator'>;
}
declare module 'prepack/lib/serializer/ResidualFunctions.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/ResidualFunctions'>;
}
declare module 'prepack/lib/serializer/ResidualHeapGraphGenerator.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/ResidualHeapGraphGenerator'>;
}
declare module 'prepack/lib/serializer/ResidualHeapRefCounter.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/ResidualHeapRefCounter'>;
}
declare module 'prepack/lib/serializer/ResidualHeapSerializer.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/ResidualHeapSerializer'>;
}
declare module 'prepack/lib/serializer/ResidualHeapValueIdentifiers.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/ResidualHeapValueIdentifiers'>;
}
declare module 'prepack/lib/serializer/ResidualHeapVisitor.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/ResidualHeapVisitor'>;
}
declare module 'prepack/lib/serializer/ResidualReactElementSerializer.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/ResidualReactElementSerializer'>;
}
declare module 'prepack/lib/serializer/ResidualReactElementVisitor.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/ResidualReactElementVisitor'>;
}
declare module 'prepack/lib/serializer/serializer.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/serializer'>;
}
declare module 'prepack/lib/serializer/statistics.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/statistics'>;
}
declare module 'prepack/lib/serializer/types.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/types'>;
}
declare module 'prepack/lib/serializer/utils.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/utils'>;
}
declare module 'prepack/lib/serializer/visitors.js' {
  declare module.exports: $Exports<'prepack/lib/serializer/visitors'>;
}
declare module 'prepack/lib/singletons.js' {
  declare module.exports: $Exports<'prepack/lib/singletons'>;
}
declare module 'prepack/lib/statistics.js' {
  declare module.exports: $Exports<'prepack/lib/statistics'>;
}
declare module 'prepack/lib/types.js' {
  declare module.exports: $Exports<'prepack/lib/types'>;
}
declare module 'prepack/lib/utils.js' {
  declare module.exports: $Exports<'prepack/lib/utils'>;
}
declare module 'prepack/lib/utils/builder.js' {
  declare module.exports: $Exports<'prepack/lib/utils/builder'>;
}
declare module 'prepack/lib/utils/ConcreteModelConverter.js' {
  declare module.exports: $Exports<'prepack/lib/utils/ConcreteModelConverter'>;
}
declare module 'prepack/lib/utils/errors.js' {
  declare module.exports: $Exports<'prepack/lib/utils/errors'>;
}
declare module 'prepack/lib/utils/flow.js' {
  declare module.exports: $Exports<'prepack/lib/utils/flow'>;
}
declare module 'prepack/lib/utils/generator.js' {
  declare module.exports: $Exports<'prepack/lib/utils/generator'>;
}
declare module 'prepack/lib/utils/havoc.js' {
  declare module.exports: $Exports<'prepack/lib/utils/havoc'>;
}
declare module 'prepack/lib/utils/HeapInspector.js' {
  declare module.exports: $Exports<'prepack/lib/utils/HeapInspector'>;
}
declare module 'prepack/lib/utils/internalizer.js' {
  declare module.exports: $Exports<'prepack/lib/utils/internalizer'>;
}
declare module 'prepack/lib/utils/json.js' {
  declare module.exports: $Exports<'prepack/lib/utils/json'>;
}
declare module 'prepack/lib/utils/JSONTokenizer.js' {
  declare module.exports: $Exports<'prepack/lib/utils/JSONTokenizer'>;
}
declare module 'prepack/lib/utils/logger.js' {
  declare module.exports: $Exports<'prepack/lib/utils/logger'>;
}
declare module 'prepack/lib/utils/modules.js' {
  declare module.exports: $Exports<'prepack/lib/utils/modules'>;
}
declare module 'prepack/lib/utils/native-to-interp.js' {
  declare module.exports: $Exports<'prepack/lib/utils/native-to-interp'>;
}
declare module 'prepack/lib/utils/parse.js' {
  declare module.exports: $Exports<'prepack/lib/utils/parse'>;
}
declare module 'prepack/lib/utils/paths.js' {
  declare module.exports: $Exports<'prepack/lib/utils/paths'>;
}
declare module 'prepack/lib/utils/simplifier.js' {
  declare module.exports: $Exports<'prepack/lib/utils/simplifier'>;
}
declare module 'prepack/lib/utils/strict.js' {
  declare module.exports: $Exports<'prepack/lib/utils/strict'>;
}
declare module 'prepack/lib/utils/traverse-fast.js' {
  declare module.exports: $Exports<'prepack/lib/utils/traverse-fast'>;
}
declare module 'prepack/lib/values/AbstractObjectValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/AbstractObjectValue'>;
}
declare module 'prepack/lib/values/AbstractValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/AbstractValue'>;
}
declare module 'prepack/lib/values/ArgumentsExotic.js' {
  declare module.exports: $Exports<'prepack/lib/values/ArgumentsExotic'>;
}
declare module 'prepack/lib/values/ArrayValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/ArrayValue'>;
}
declare module 'prepack/lib/values/BooleanValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/BooleanValue'>;
}
declare module 'prepack/lib/values/BoundFunctionValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/BoundFunctionValue'>;
}
declare module 'prepack/lib/values/ConcreteValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/ConcreteValue'>;
}
declare module 'prepack/lib/values/ECMAScriptFunctionValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/ECMAScriptFunctionValue'>;
}
declare module 'prepack/lib/values/ECMAScriptSourceFunctionValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/ECMAScriptSourceFunctionValue'>;
}
declare module 'prepack/lib/values/EmptyValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/EmptyValue'>;
}
declare module 'prepack/lib/values/FunctionValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/FunctionValue'>;
}
declare module 'prepack/lib/values/index.js' {
  declare module.exports: $Exports<'prepack/lib/values/index'>;
}
declare module 'prepack/lib/values/IntegerIndexedExotic.js' {
  declare module.exports: $Exports<'prepack/lib/values/IntegerIndexedExotic'>;
}
declare module 'prepack/lib/values/NativeFunctionValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/NativeFunctionValue'>;
}
declare module 'prepack/lib/values/NullValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/NullValue'>;
}
declare module 'prepack/lib/values/NumberValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/NumberValue'>;
}
declare module 'prepack/lib/values/ObjectValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/ObjectValue'>;
}
declare module 'prepack/lib/values/PrimitiveValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/PrimitiveValue'>;
}
declare module 'prepack/lib/values/ProxyValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/ProxyValue'>;
}
declare module 'prepack/lib/values/StringExotic.js' {
  declare module.exports: $Exports<'prepack/lib/values/StringExotic'>;
}
declare module 'prepack/lib/values/StringValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/StringValue'>;
}
declare module 'prepack/lib/values/SymbolValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/SymbolValue'>;
}
declare module 'prepack/lib/values/UndefinedValue.js' {
  declare module.exports: $Exports<'prepack/lib/values/UndefinedValue'>;
}
declare module 'prepack/lib/values/Value.js' {
  declare module.exports: $Exports<'prepack/lib/values/Value'>;
}
