// flow-typed signature: 18b7041635b42c19211cbfc9c3b270be
// flow-typed version: <<STUB>>/puppeteer-core_v1.14.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'puppeteer-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'puppeteer-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'puppeteer-core/DeviceDescriptors' {
  declare module.exports: any;
}

declare module 'puppeteer-core/Errors' {
  declare module.exports: any;
}

declare module 'puppeteer-core/install' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Accessibility' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/api' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Browser' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/BrowserFetcher' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Connection' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Coverage' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Dialog' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/DOMWorld' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/EmulationManager' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Errors' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Events' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/ExecutionContext' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/FrameManager' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/helper' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Input' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/JSHandle' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Launcher' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/LifecycleWatcher' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Multimap' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/NetworkManager' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Page' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/PipeTransport' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Target' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/TaskQueue' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/TimeoutSettings' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Tracing' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/USKeyboardLayout' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/WebSocketTransport' {
  declare module.exports: any;
}

declare module 'puppeteer-core/lib/Worker' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Accessibility' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/api' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Browser' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/BrowserFetcher' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Connection' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Coverage' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Dialog' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/DOMWorld' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/EmulationManager' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Errors' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Events' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/ExecutionContext' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/FrameManager' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/helper' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Input' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/JSHandle' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Launcher' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/LifecycleWatcher' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Multimap' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/NetworkManager' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Page' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/PipeTransport' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Target' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/TaskQueue' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/TimeoutSettings' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Tracing' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/USKeyboardLayout' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/WebSocketTransport' {
  declare module.exports: any;
}

declare module 'puppeteer-core/node6/lib/Worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'puppeteer-core/DeviceDescriptors.js' {
  declare module.exports: $Exports<'puppeteer-core/DeviceDescriptors'>;
}
declare module 'puppeteer-core/Errors.js' {
  declare module.exports: $Exports<'puppeteer-core/Errors'>;
}
declare module 'puppeteer-core/index' {
  declare module.exports: $Exports<'puppeteer-core'>;
}
declare module 'puppeteer-core/index.js' {
  declare module.exports: $Exports<'puppeteer-core'>;
}
declare module 'puppeteer-core/install.js' {
  declare module.exports: $Exports<'puppeteer-core/install'>;
}
declare module 'puppeteer-core/lib/Accessibility.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Accessibility'>;
}
declare module 'puppeteer-core/lib/api.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/api'>;
}
declare module 'puppeteer-core/lib/Browser.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Browser'>;
}
declare module 'puppeteer-core/lib/BrowserFetcher.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/BrowserFetcher'>;
}
declare module 'puppeteer-core/lib/Connection.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Connection'>;
}
declare module 'puppeteer-core/lib/Coverage.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Coverage'>;
}
declare module 'puppeteer-core/lib/Dialog.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Dialog'>;
}
declare module 'puppeteer-core/lib/DOMWorld.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/DOMWorld'>;
}
declare module 'puppeteer-core/lib/EmulationManager.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/EmulationManager'>;
}
declare module 'puppeteer-core/lib/Errors.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Errors'>;
}
declare module 'puppeteer-core/lib/Events.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Events'>;
}
declare module 'puppeteer-core/lib/ExecutionContext.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/ExecutionContext'>;
}
declare module 'puppeteer-core/lib/FrameManager.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/FrameManager'>;
}
declare module 'puppeteer-core/lib/helper.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/helper'>;
}
declare module 'puppeteer-core/lib/Input.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Input'>;
}
declare module 'puppeteer-core/lib/JSHandle.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/JSHandle'>;
}
declare module 'puppeteer-core/lib/Launcher.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Launcher'>;
}
declare module 'puppeteer-core/lib/LifecycleWatcher.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/LifecycleWatcher'>;
}
declare module 'puppeteer-core/lib/Multimap.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Multimap'>;
}
declare module 'puppeteer-core/lib/NetworkManager.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/NetworkManager'>;
}
declare module 'puppeteer-core/lib/Page.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Page'>;
}
declare module 'puppeteer-core/lib/PipeTransport.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/PipeTransport'>;
}
declare module 'puppeteer-core/lib/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Puppeteer'>;
}
declare module 'puppeteer-core/lib/Target.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Target'>;
}
declare module 'puppeteer-core/lib/TaskQueue.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/TaskQueue'>;
}
declare module 'puppeteer-core/lib/TimeoutSettings.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/TimeoutSettings'>;
}
declare module 'puppeteer-core/lib/Tracing.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Tracing'>;
}
declare module 'puppeteer-core/lib/USKeyboardLayout.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/USKeyboardLayout'>;
}
declare module 'puppeteer-core/lib/WebSocketTransport.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/WebSocketTransport'>;
}
declare module 'puppeteer-core/lib/Worker.js' {
  declare module.exports: $Exports<'puppeteer-core/lib/Worker'>;
}
declare module 'puppeteer-core/node6/lib/Accessibility.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Accessibility'>;
}
declare module 'puppeteer-core/node6/lib/api.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/api'>;
}
declare module 'puppeteer-core/node6/lib/Browser.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Browser'>;
}
declare module 'puppeteer-core/node6/lib/BrowserFetcher.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/BrowserFetcher'>;
}
declare module 'puppeteer-core/node6/lib/Connection.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Connection'>;
}
declare module 'puppeteer-core/node6/lib/Coverage.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Coverage'>;
}
declare module 'puppeteer-core/node6/lib/Dialog.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Dialog'>;
}
declare module 'puppeteer-core/node6/lib/DOMWorld.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/DOMWorld'>;
}
declare module 'puppeteer-core/node6/lib/EmulationManager.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/EmulationManager'>;
}
declare module 'puppeteer-core/node6/lib/Errors.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Errors'>;
}
declare module 'puppeteer-core/node6/lib/Events.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Events'>;
}
declare module 'puppeteer-core/node6/lib/ExecutionContext.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/ExecutionContext'>;
}
declare module 'puppeteer-core/node6/lib/FrameManager.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/FrameManager'>;
}
declare module 'puppeteer-core/node6/lib/helper.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/helper'>;
}
declare module 'puppeteer-core/node6/lib/Input.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Input'>;
}
declare module 'puppeteer-core/node6/lib/JSHandle.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/JSHandle'>;
}
declare module 'puppeteer-core/node6/lib/Launcher.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Launcher'>;
}
declare module 'puppeteer-core/node6/lib/LifecycleWatcher.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/LifecycleWatcher'>;
}
declare module 'puppeteer-core/node6/lib/Multimap.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Multimap'>;
}
declare module 'puppeteer-core/node6/lib/NetworkManager.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/NetworkManager'>;
}
declare module 'puppeteer-core/node6/lib/Page.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Page'>;
}
declare module 'puppeteer-core/node6/lib/PipeTransport.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/PipeTransport'>;
}
declare module 'puppeteer-core/node6/lib/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Puppeteer'>;
}
declare module 'puppeteer-core/node6/lib/Target.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Target'>;
}
declare module 'puppeteer-core/node6/lib/TaskQueue.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/TaskQueue'>;
}
declare module 'puppeteer-core/node6/lib/TimeoutSettings.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/TimeoutSettings'>;
}
declare module 'puppeteer-core/node6/lib/Tracing.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Tracing'>;
}
declare module 'puppeteer-core/node6/lib/USKeyboardLayout.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/USKeyboardLayout'>;
}
declare module 'puppeteer-core/node6/lib/WebSocketTransport.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/WebSocketTransport'>;
}
declare module 'puppeteer-core/node6/lib/Worker.js' {
  declare module.exports: $Exports<'puppeteer-core/node6/lib/Worker'>;
}
