// flow-typed signature: a5f4fa36ed368fa4a1dadd666a01b276
// flow-typed version: <<STUB>>/shrink-ray-current_v2.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shrink-ray-current'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shrink-ray-current' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shrink-ray-current/prepublish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shrink-ray-current/index' {
  declare module.exports: $Exports<'shrink-ray-current'>;
}
declare module 'shrink-ray-current/index.js' {
  declare module.exports: $Exports<'shrink-ray-current'>;
}
declare module 'shrink-ray-current/prepublish.js' {
  declare module.exports: $Exports<'shrink-ray-current/prepublish'>;
}
