// flow-typed signature: a5cc9ceedb523e6dd95888fea1c749fa
// flow-typed version: <<STUB>>/simpl-schema_v1.1.2/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simpl-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simpl-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simpl-schema/dist/clean' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/clean/AutoValueRunner' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/clean/convertToProperType' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/clean/getPositionsForAutoValue' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/clean/setAutoValues' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/defaultMessages' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/doValidation' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/expandShorthand' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/humanize' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/main' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/regExp' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/SimpleSchema' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/SimpleSchemaGroup' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/getLastPartOfKey' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/utility/index' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/allowedValuesValidator' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/doArrayChecks' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/doDateChecks' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/doNumberChecks' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/doStringChecks' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/requiredValidator' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/validation/typeValidator' {
  declare module.exports: any;
}

declare module 'simpl-schema/dist/ValidationContext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simpl-schema/dist/clean.js' {
  declare module.exports: $Exports<'simpl-schema/dist/clean'>;
}
declare module 'simpl-schema/dist/clean/AutoValueRunner.js' {
  declare module.exports: $Exports<'simpl-schema/dist/clean/AutoValueRunner'>;
}
declare module 'simpl-schema/dist/clean/convertToProperType.js' {
  declare module.exports: $Exports<'simpl-schema/dist/clean/convertToProperType'>;
}
declare module 'simpl-schema/dist/clean/getPositionsForAutoValue.js' {
  declare module.exports: $Exports<'simpl-schema/dist/clean/getPositionsForAutoValue'>;
}
declare module 'simpl-schema/dist/clean/setAutoValues.js' {
  declare module.exports: $Exports<'simpl-schema/dist/clean/setAutoValues'>;
}
declare module 'simpl-schema/dist/defaultMessages.js' {
  declare module.exports: $Exports<'simpl-schema/dist/defaultMessages'>;
}
declare module 'simpl-schema/dist/doValidation.js' {
  declare module.exports: $Exports<'simpl-schema/dist/doValidation'>;
}
declare module 'simpl-schema/dist/expandShorthand.js' {
  declare module.exports: $Exports<'simpl-schema/dist/expandShorthand'>;
}
declare module 'simpl-schema/dist/humanize.js' {
  declare module.exports: $Exports<'simpl-schema/dist/humanize'>;
}
declare module 'simpl-schema/dist/main.js' {
  declare module.exports: $Exports<'simpl-schema/dist/main'>;
}
declare module 'simpl-schema/dist/regExp.js' {
  declare module.exports: $Exports<'simpl-schema/dist/regExp'>;
}
declare module 'simpl-schema/dist/SimpleSchema.js' {
  declare module.exports: $Exports<'simpl-schema/dist/SimpleSchema'>;
}
declare module 'simpl-schema/dist/SimpleSchemaGroup.js' {
  declare module.exports: $Exports<'simpl-schema/dist/SimpleSchemaGroup'>;
}
declare module 'simpl-schema/dist/utility/getLastPartOfKey.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/getLastPartOfKey'>;
}
declare module 'simpl-schema/dist/utility/index.js' {
  declare module.exports: $Exports<'simpl-schema/dist/utility/index'>;
}
declare module 'simpl-schema/dist/validation/allowedValuesValidator.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/allowedValuesValidator'>;
}
declare module 'simpl-schema/dist/validation/doArrayChecks.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/doArrayChecks'>;
}
declare module 'simpl-schema/dist/validation/doDateChecks.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/doDateChecks'>;
}
declare module 'simpl-schema/dist/validation/doNumberChecks.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/doNumberChecks'>;
}
declare module 'simpl-schema/dist/validation/doStringChecks.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/doStringChecks'>;
}
declare module 'simpl-schema/dist/validation/requiredValidator.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/requiredValidator'>;
}
declare module 'simpl-schema/dist/validation/typeValidator.js' {
  declare module.exports: $Exports<'simpl-schema/dist/validation/typeValidator'>;
}
declare module 'simpl-schema/dist/ValidationContext.js' {
  declare module.exports: $Exports<'simpl-schema/dist/ValidationContext'>;
}
