// flow-typed signature: bcab3f607219df867e9a53289f1c0e31
// flow-typed version: <<STUB>>/terser_v3.8.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terser/dist/browser.bundle' {
  declare module.exports: any;
}

declare module 'terser/lib/ast' {
  declare module.exports: any;
}

declare module 'terser/lib/compress' {
  declare module.exports: any;
}

declare module 'terser/lib/minify' {
  declare module.exports: any;
}

declare module 'terser/lib/mozilla-ast' {
  declare module.exports: any;
}

declare module 'terser/lib/output' {
  declare module.exports: any;
}

declare module 'terser/lib/parse' {
  declare module.exports: any;
}

declare module 'terser/lib/propmangle' {
  declare module.exports: any;
}

declare module 'terser/lib/scope' {
  declare module.exports: any;
}

declare module 'terser/lib/sourcemap' {
  declare module.exports: any;
}

declare module 'terser/lib/transform' {
  declare module.exports: any;
}

declare module 'terser/lib/utils' {
  declare module.exports: any;
}

declare module 'terser/tools/colorless-console' {
  declare module.exports: any;
}

declare module 'terser/tools/exit' {
  declare module.exports: any;
}

declare module 'terser/tools/exports' {
  declare module.exports: any;
}

declare module 'terser/tools/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terser/dist/browser.bundle.js' {
  declare module.exports: $Exports<'terser/dist/browser.bundle'>;
}
declare module 'terser/lib/ast.js' {
  declare module.exports: $Exports<'terser/lib/ast'>;
}
declare module 'terser/lib/compress.js' {
  declare module.exports: $Exports<'terser/lib/compress'>;
}
declare module 'terser/lib/minify.js' {
  declare module.exports: $Exports<'terser/lib/minify'>;
}
declare module 'terser/lib/mozilla-ast.js' {
  declare module.exports: $Exports<'terser/lib/mozilla-ast'>;
}
declare module 'terser/lib/output.js' {
  declare module.exports: $Exports<'terser/lib/output'>;
}
declare module 'terser/lib/parse.js' {
  declare module.exports: $Exports<'terser/lib/parse'>;
}
declare module 'terser/lib/propmangle.js' {
  declare module.exports: $Exports<'terser/lib/propmangle'>;
}
declare module 'terser/lib/scope.js' {
  declare module.exports: $Exports<'terser/lib/scope'>;
}
declare module 'terser/lib/sourcemap.js' {
  declare module.exports: $Exports<'terser/lib/sourcemap'>;
}
declare module 'terser/lib/transform.js' {
  declare module.exports: $Exports<'terser/lib/transform'>;
}
declare module 'terser/lib/utils.js' {
  declare module.exports: $Exports<'terser/lib/utils'>;
}
declare module 'terser/tools/colorless-console.js' {
  declare module.exports: $Exports<'terser/tools/colorless-console'>;
}
declare module 'terser/tools/exit.js' {
  declare module.exports: $Exports<'terser/tools/exit'>;
}
declare module 'terser/tools/exports.js' {
  declare module.exports: $Exports<'terser/tools/exports'>;
}
declare module 'terser/tools/node.js' {
  declare module.exports: $Exports<'terser/tools/node'>;
}
